name: 'Platformio build'
description: 'Building platformio projects'
inputs:
   command:
     description: 'Command'
     required: true
     default: pio run
runs:
  using: 'docker'
  image: 'docker://sergeyladanov/platformio:v2'
  args:
     - ${{ inputs.command }}
 
